"""Dark Slate theme - OLED-optimized deep dark theme.

Deep slate/black backgrounds with indigo accent. Optimized for OLED displays.
"""

DARK_SLATE_THEME = {
    "metadata": {
        "name": "Dark Slate",
        "author": "Newsletter Reader",
        "version": "1.0.0",
        "description": "Deep slate OLED-optimized dark theme",
        "base": "dark",
    },
    "colors": {
        "light": {
            "bg_primary": "#FAFAFA",
            "bg_secondary": "#F5F5F5",
            "bg_tertiary": "#EEEEEE",
            "bg_elevated": "#FFFFFF",
            "text_primary": "#1A1A1A",
            "text_secondary": "#525252",
            "text_tertiary": "#8A8A8A",
            "text_disabled": "#BDBDBD",
            "border_default": "#E0E0E0",
            "border_subtle": "#EEEEEE",
            "border_strong": "#BDBDBD",
            "hover": "#F5F5F5",
            "active": "#EEEEEE",
            "focus_ring": "#6366F1",
            "accent": "#6366F1",
            "accent_hover": "#4F46E5",
            "accent_muted": "#EEF2FF",
            "success": "#22C55E",
            "success_muted": "#DCFCE7",
            "warning": "#F59E0B",
            "warning_muted": "#FEF3C7",
            "error": "#EF4444",
            "error_muted": "#FEE2E2",
            "unread_dot": "#6366F1",
            "star_active": "#F59E0B",
            "star_inactive": "#BDBDBD",
        },
        "dark": {
            "bg_primary": "#000000",
            "bg_secondary": "#0A0A0A",
            "bg_tertiary": "#171717",
            "bg_elevated": "#0A0A0A",
            "text_primary": "#FAFAFA",
            "text_secondary": "#A3A3A3",
            "text_tertiary": "#737373",
            "text_disabled": "#525252",
            "border_default": "#262626",
            "border_subtle": "#171717",
            "border_strong": "#404040",
            "hover": "#0A0A0A",
            "active": "#171717",
            "focus_ring": "#818CF8",
            "accent": "#818CF8",
            "accent_hover": "#6366F1",
            "accent_muted": "#1E1B4B",
            "success": "#4ADE80",
            "success_muted": "#14532D",
            "warning": "#FBBF24",
            "warning_muted": "#78350F",
            "error": "#F87171",
            "error_muted": "#7F1D1D",
            "unread_dot": "#818CF8",
            "star_active": "#FBBF24",
            "star_inactive": "#404040",
        },
    },
}
