"""Default theme - Sophistication & Trust palette.

Cool slate tones with blue accent. The default theme for Newsletter Reader.
"""

DEFAULT_THEME = {
    "metadata": {
        "name": "Default",
        "author": "Newsletter Reader",
        "version": "1.0.0",
        "description": "Sophistication & Trust - cool slate tones with blue accent",
        "base": "light",
    },
    "colors": {
        "light": {
            "bg_primary": "#FFFFFF",
            "bg_secondary": "#F8FAFC",
            "bg_tertiary": "#F1F5F9",
            "bg_elevated": "#FFFFFF",
            "text_primary": "#0F172A",
            "text_secondary": "#475569",
            "text_tertiary": "#94A3B8",
            "text_disabled": "#CBD5E1",
            "border_default": "#E2E8F0",
            "border_subtle": "#F1F5F9",
            "border_strong": "#CBD5E1",
            "hover": "#F8FAFC",
            "active": "#F1F5F9",
            "focus_ring": "#3B82F6",
            "accent": "#3B82F6",
            "accent_hover": "#2563EB",
            "accent_muted": "#DBEAFE",
            "success": "#22C55E",
            "success_muted": "#DCFCE7",
            "warning": "#F59E0B",
            "warning_muted": "#FEF3C7",
            "error": "#EF4444",
            "error_muted": "#FEE2E2",
            "unread_dot": "#3B82F6",
            "star_active": "#F59E0B",
            "star_inactive": "#CBD5E1",
        },
        "dark": {
            "bg_primary": "#0F172A",
            "bg_secondary": "#1E293B",
            "bg_tertiary": "#334155",
            "bg_elevated": "#1E293B",
            "text_primary": "#F8FAFC",
            "text_secondary": "#CBD5E1",
            "text_tertiary": "#94A3B8",
            "text_disabled": "#64748B",
            "border_default": "#334155",
            "border_subtle": "#1E293B",
            "border_strong": "#475569",
            "hover": "#1E293B",
            "active": "#334155",
            "focus_ring": "#60A5FA",
            "accent": "#60A5FA",
            "accent_hover": "#3B82F6",
            "accent_muted": "#1E3A5F",
            "success": "#4ADE80",
            "success_muted": "#14532D",
            "warning": "#FBBF24",
            "warning_muted": "#78350F",
            "error": "#F87171",
            "error_muted": "#7F1D1D",
            "unread_dot": "#60A5FA",
            "star_active": "#FBBF24",
            "star_inactive": "#475569",
        },
    },
}
