"""Light Clean theme - Warm, modern, minimal.

Clean light theme with teal accent for a fresh, modern look.
"""

LIGHT_CLEAN_THEME = {
    "metadata": {
        "name": "Light Clean",
        "author": "Newsletter Reader",
        "version": "1.0.0",
        "description": "Warm, modern light theme with teal accent",
        "base": "light",
    },
    "colors": {
        "light": {
            "bg_primary": "#FFFFFF",
            "bg_secondary": "#F8FAFC",
            "bg_tertiary": "#F1F5F9",
            "bg_elevated": "#FFFFFF",
            "text_primary": "#0F172A",
            "text_secondary": "#475569",
            "text_tertiary": "#94A3B8",
            "text_disabled": "#CBD5E1",
            "border_default": "#E2E8F0",
            "border_subtle": "#F1F5F9",
            "border_strong": "#CBD5E1",
            "hover": "#F8FAFC",
            "active": "#F1F5F9",
            "focus_ring": "#14B8A6",
            "accent": "#14B8A6",
            "accent_hover": "#0D9488",
            "accent_muted": "#CCFBF1",
            "success": "#10B981",
            "success_muted": "#D1FAE5",
            "warning": "#F59E0B",
            "warning_muted": "#FEF3C7",
            "error": "#EF4444",
            "error_muted": "#FEE2E2",
            "unread_dot": "#14B8A6",
            "star_active": "#F59E0B",
            "star_inactive": "#CBD5E1",
        },
        "dark": {
            "bg_primary": "#0F172A",
            "bg_secondary": "#1E293B",
            "bg_tertiary": "#334155",
            "bg_elevated": "#1E293B",
            "text_primary": "#F8FAFC",
            "text_secondary": "#CBD5E1",
            "text_tertiary": "#94A3B8",
            "text_disabled": "#64748B",
            "border_default": "#334155",
            "border_subtle": "#1E293B",
            "border_strong": "#475569",
            "hover": "#1E293B",
            "active": "#334155",
            "focus_ring": "#2DD4BF",
            "accent": "#2DD4BF",
            "accent_hover": "#14B8A6",
            "accent_muted": "#134E4A",
            "success": "#34D399",
            "success_muted": "#065F46",
            "warning": "#FBBF24",
            "warning_muted": "#78350F",
            "error": "#F87171",
            "error_muted": "#7F1D1D",
            "unread_dot": "#2DD4BF",
            "star_active": "#FBBF24",
            "star_inactive": "#475569",
        },
    },
}
