"""Midnight theme - Dramatic dark with magenta accent.

True black OLED-friendly background with vibrant magenta/fuchsia accent.
"""

MIDNIGHT_THEME = {
    "metadata": {
        "name": "Midnight",
        "author": "Newsletter Reader",
        "version": "1.0.0",
        "description": "Dramatic dark theme with magenta/fuchsia accent",
        "base": "dark",
    },
    "colors": {
        "light": {
            "bg_primary": "#FDFAFF",
            "bg_secondary": "#F8F0FC",
            "bg_tertiary": "#F3E8FA",
            "bg_elevated": "#FFFFFF",
            "text_primary": "#1A0A24",
            "text_secondary": "#4A3456",
            "text_tertiary": "#8B6A9E",
            "text_disabled": "#C4A8D4",
            "border_default": "#E8D4F0",
            "border_subtle": "#F3E8FA",
            "border_strong": "#D4B8E4",
            "hover": "#F8F0FC",
            "active": "#F3E8FA",
            "focus_ring": "#D946EF",
            "accent": "#D946EF",
            "accent_hover": "#C026D3",
            "accent_muted": "#FAE8FF",
            "success": "#22C55E",
            "success_muted": "#DCFCE7",
            "warning": "#F59E0B",
            "warning_muted": "#FEF3C7",
            "error": "#EF4444",
            "error_muted": "#FEE2E2",
            "unread_dot": "#D946EF",
            "star_active": "#F59E0B",
            "star_inactive": "#C4A8D4",
        },
        "dark": {
            "bg_primary": "#0D0D0D",
            "bg_secondary": "#141414",
            "bg_tertiary": "#1F1F1F",
            "bg_elevated": "#181818",
            "text_primary": "#FAFAFA",
            "text_secondary": "#B8B8B8",
            "text_tertiary": "#787878",
            "text_disabled": "#484848",
            "border_default": "#2E2E2E",
            "border_subtle": "#1F1F1F",
            "border_strong": "#444444",
            "hover": "#1A1A1A",
            "active": "#252525",
            "focus_ring": "#E879F9",
            "accent": "#E879F9",
            "accent_hover": "#D946EF",
            "accent_muted": "#3B0764",
            "success": "#4ADE80",
            "success_muted": "#14532D",
            "warning": "#FBBF24",
            "warning_muted": "#78350F",
            "error": "#F87171",
            "error_muted": "#7F1D1D",
            "unread_dot": "#E879F9",
            "star_active": "#FBBF24",
            "star_inactive": "#444444",
        },
    },
}
