"""Remove app_credentials table

Revision ID: c6a92555ba56
Revises: 
Create Date: 2026-01-08 22:05:09.989117
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6a92555ba56'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_credentials')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_credentials',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_id_encrypted', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('client_secret_encrypted', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_configured', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('app_credentials_pkey'))
    )
    # ### end Alembic commands ###
