"""Add last_email_received_at to newsletters

Revision ID: a5a1ab541a29
Revises: ca84200684b5
Create Date: 2026-01-10 15:47:40.542886
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5a1ab541a29'
down_revision: Union[str, None] = 'ca84200684b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsletters', sa.Column('last_email_received_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('newsletters', 'last_email_received_at')
    # ### end Alembic commands ###
