"""add email summary and llm settings fields

Revision ID: 60ea93dbedf5
Revises: 31fb1e510aca
Create Date: 2026-01-25 22:42:55.124015
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60ea93dbedf5'
down_revision: Union[str, None] = '31fb1e510aca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('summary_model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('summarized_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_enabled', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('llm_api_base_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('llm_api_key_encrypted', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('llm_model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('llm_max_tokens', sa.Integer(), server_default=sa.text('(500)'), nullable=False))
        batch_op.add_column(sa.Column('llm_temperature', sa.Float(), server_default=sa.text('(0.3)'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('llm_temperature')
        batch_op.drop_column('llm_max_tokens')
        batch_op.drop_column('llm_model')
        batch_op.drop_column('llm_api_key_encrypted')
        batch_op.drop_column('llm_api_base_url')
        batch_op.drop_column('llm_enabled')

    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_column('summarized_at')
        batch_op.drop_column('summary_model')
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
