"""add_color_secondary_for_gradients

Revision ID: 31fb1e510aca
Revises: b7c84d62fa12
Create Date: 2026-01-24 14:42:07.756330
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31fb1e510aca'
down_revision: Union[str, None] = 'b7c84d62fa12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_secondary', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletters', schema=None) as batch_op:
        batch_op.drop_column('color_secondary')

    # ### end Alembic commands ###
